---
title: "Multisite Short Run SDA Analysis"
date: 11/01/2019
author: "Marissa Kivi"
---
Sites: Harvard Forest, North Round Pond, Rooster Hill, Goose Egg
Site Inputs: workflow id, lat, lon, observation data

TO DO: 
- Since we are still only considering a few sites and some species are not represented at all, we might need to represent which site each point comes from in the case that the site and combination of species is not influencing results more than environmental variables. 

```{R, echo = FALSE, include = FALSE}
rm(list=ls())
library(mvtnorm)
library(PEcAn.workflow)
library(PEcAn.settings)
library(ggplot2)
library(gridExtra)
library(boot)
library(reshape2)
library(dplyr)
library(class)
library(GGally)
library(randomForest)

source('~/VM_scripts/gather_sda_data.R')
```

# Step 1: Prepare data

## A. Gather data for each site 

```{R, echo = FALSE}
# Site 1: Goose Egg
#workflowID = '140000000--'
#settings.GE = read.settings(paste0('/data/workflows/PEcAn_',workflowID,'/pecan.SDA.xml'))
#lat = 
#lon = 
#spp.GE = as.vector(sapply(settings.GE$pfts, function(pft){pft$name}))
#load(paste0('/data/dbfiles/sda.obs.GE.Rdata'))
#obs.list.GE = obs.list
#GE.data = gather_sda_data()

# Site 2: Harvard Forest
workflowID = '14000000018'
settings.HF = read.settings(paste0('/data/workflows/PEcAn_',workflowID,'/pecan.SDA.xml'))
lat = 42.53
lon = -72.18
spp.HF = as.vector(sapply(settings.HF$pfts, function(pft){pft$name}))
load(paste0('/data/dbfiles/sda.obs.Rdata'))
#load(paste0('/data/dbfiles/sda.obs.HF.Rdata'))
obs.list.HF = obs.list
site = 'HF'
HF.data = gather_sda_data(settings = settings.HF, lat, lon, obs.list=obs.list.HF, init=site)

# Site 3: North Round Pond
#workflowID = '140000000--'
#settings.NRP = read.settings(paste0('/data/workflows/PEcAn_',workflowID,'/pecan.SDA.xml'))
#lat = 
#lon = 
#spp.NRP = as.vector(sapply(settings.NRP$pfts, function(pft){pft$name}))
#load(paste0('/data/dbfiles/sda.obs.NRP.Rdata'))
#obs.list.NRP = obs.list
#NRP.data = gather_sda_data()

# Site 4: Rooster Hill
workflowID = '14000000036'
settings.RH = read.settings(paste0('/data/workflows/PEcAn_',workflowID,'/pecan.SDA.xml'))
lat = 43.2309
lon = -74.5267
spp.RH = as.vector(sapply(settings.RH$pfts, function(pft){pft$name}))
load(paste0('/data/dbfiles/sda.obs.RH.Rdata'))
obs.mean = obs.list$obs.mean[as.numeric(substr(names(obs.list$obs.mean),1,4)) %in% c(1960:2010)]
obs.cov = obs.list$obs.cov[as.numeric(substr(names(obs.list$obs.cov),1,4)) %in% c(1960:2010)]
obs.list.RH = list(obs.mean = obs.mean, obs.cov = obs.cov)
site = 'RH'
RH.data = gather_sda_data(settings = settings.RH, lat, lon, obs.list=obs.list.RH, init=site)

```

## B. Condense site data 

Group data from all sites into a few variables. 

```{R, echo = F}
# Compile data 

#data = list(GE.data, HF.data, NRP.data, RH.data)
data = list(HF.data, RH.data)

# Step 2 and 3 
#param.melt = rbind(GE.data$param.melt, HF.data$param.melt, NRP.data$param.melt, RH.data$param.melt)
#bias.melt = rbind(GE.data$bias.melt, HF.data$bias.melt, NRP.data$bias.melt, RH.data$bias.melt) %>% mutate(class = (bias <= abs(0.25)))
param.melt = rbind(HF.data$param.melt, RH.data$param.melt)
bias.melt = rbind(HF.data$bias.melt, RH.data$bias.melt) %>% mutate(class = (bias <= abs(0.25)))

good.ensembles = c(bias.melt %>% group_by(ensemble) %>% 
  summarize(class = ifelse(mean(abs(bias)) <= 0.25,1,0)) %>%
  filter(class == 1) %>%
  dplyr::select(ensemble))

sites = unique(param.melt$site)

#all.spp = unique(c(spp.GE, spp.HF, spp.NRP, spp.RH))
#spp.list = list(spp.GE = spp.GE, spp.HF = spp.HF, spp.NRP = spp.NRP, spp.RH = spp.RH)
all.spp = unique(c(spp.HF, spp.RH))
spp.list = list(spp.HF = spp.HF, spp.RH = spp.RH)

run.list = list()
for (s in all.spp){
  compiled = NULL
  for (site in 1:length(spp.list)){
    if (s %in% spp.list[[site]]){
      ind = which(spp.list[[site]] == s)
      if(is.null(compiled)){
        compiled = data[[site]]$run.list[[ind]]
      }else{
        compiled = rbind(compiled, data[[site]]$run.list[[ind]])
      }
    }
  }
  run.list[[s]] = compiled
}

# Other important variables: 
param.names = c('DMAX','DMIN','B3','B2','AGEMX','G','SPRTND','SPRTMN','SPRTMX','MPLANT','D3','FROST','CM1','CM2','CM3','CM4','CM5','FWT','SLTA','SLTB')
```

# Step 2: Determine sensitive parameters 

## A. Determine single significant parameter predictors of accuracy 

Consider ranges of parameter values that are consistently leading to poor model predictions. 
This step includes all ensembles, good and bad. 

```{R, message=FALSE , warnings=FALSE, echo = FALSE}
# organize data
data2 = left_join(bias.melt, param.melt, id = c('site','ensemble')) %>% group_by(site,ensemble,p.name,species) %>%
  summarize(p.value = mean(p.value)) %>% ungroup()

# recast data frame into usable matrix 
df2 = dcast(data = data2, formula = ensemble ~ species + p.name,fun.aggregate = sum,value.var = "p.value")
df2$class = ifelse(df2$ensemble %in% good.ensembles$ensemble, 1, 0)
df2 = df2 %>% dplyr::select(-ensemble)

# find importance rankings for each parameter
forest1=randomForest(factor(class)~., data=df2)
vi_imp = importance(forest1)
vi_sort = sort(vi_imp, decreasing = TRUE, index.return=TRUE)
vi.df = data.frame(par = rownames(vi_imp)[vi_sort$ix], imp = vi_sort$x)
print(barplot(vi.df$imp, main = 'Importance Rankings of Spp Parameters'))
```


```{R, message=FALSE, warnings=FALSE, echo = FALSE}

### ADJUST SCRIPT HERE 
# cut off variables at elbow seen in above bar plot
vi.df.red = vi.df %>% filter(imp>=0.6) 

# save objects
obj1 = list()
nvars = length(vi.df.red$par)

# plot each variable found to be important
for (i in 1:nvars){
  names = strsplit(toString(vi.df.red$par[i]), '_')
  spp.name = paste0(names[[1]][1],'_',names[[1]][2])
  p.num = as.numeric(names[[1]][3])
  
  vals = data2 %>% filter(species == spp.name, p.name == p.num) 
  vals$class = ifelse(vals$ensemble %in% good.ensembles$ensemble, 1, 0)
  
  # save in list
  obj1[[i]] = paste(spp.name, param.names[p.num])
  
  # plot
  plt = ggplot(vals) + 
    geom_histogram(aes(x=p.value, fill = as.factor(class))) +
    labs(title = paste(spp.name, param.names[p.num]),
         x = 'parameter value')
  print(plt)
}

```

## B. Look at significant interactions between variables for predicting model accuracy 

Consider combinations of parameters that are consistently leading to inaccurate model predictions. 

Consider only the top ten most important species parameters using importance ranking wih random forest. 

```{R,message=FALSE, warnings=FALSE, echo = FALSE}

# consider interactions between the top ten important spp parameters
df2a = data.frame(ensemble = unique(data2$ensemble))
vi.df = vi.df %>% arrange(desc(imp)) 

track = vector()
k = 1
# get data prepped as interactions
for (i in 1:9){
  
  print(i)
  
  for (j in (i+1):10){
    
    # get basic info on parameter
    names = strsplit(toString(vi.df$par[i]), '_')
    sp1 = paste0(names[[1]][1],'_',names[[1]][2])
    p1 = as.numeric(names[[1]][3])
  
    names = strsplit(toString(vi.df$par[j]), '_')
    sp2 = paste0(names[[1]][1],'_',names[[1]][2])
    p2 = as.numeric(names[[1]][3])
    
    # get sites shared between species if there are any
    shared.sites = sapply(spp.list, function(site){(sp1 %in% site) & (sp2 %in% site)})
    sites.needed = sites[shared.sites]
    if (!any(shared.sites)) next
    
    # get parameter values
    dat1 = data2 %>% filter(species == sp1, p.name == p1, site %in% sites.needed) %>%
      dplyr::select(p.value,ensemble)
    dat2 = data2 %>% filter(species == sp2, p.name == p2, site %in% sites.needed) %>%
      dplyr::select(p.value,ensemble)
    ints = left_join(dat1, dat2, by = 'ensemble') %>%
      mutate(inter=p.value.x*p.value.y) %>% dplyr::select(ensemble,inter)
    df2a = left_join(df2a, ints, by = 'ensemble')
    
    track[[k]] = paste(sp1,'-',p1,'-',sp2,'-',p2)
    k = k + 1
  }
}

names(df2a) = c('ensemble',paste0('inter',c(1:length(track))))
df2a$class  = ifelse(df2a$ensemble %in% good.ensembles$ensemble,1,0)
df2a = df2a %>% dplyr::select(-ensemble)

# find importance rankings for each parameter
forest2=randomForest(factor(class)~., data=df2a, na.action=na.omit)
vi_imp2 = importance(forest2)
vi_sort2 = sort(vi_imp2, decreasing = TRUE, index.return=TRUE)
vi.df2 = data.frame(par = rownames(vi_imp2)[vi_sort2$ix], imp = vi_sort2$x)
print(barplot(vi.df2$imp))

```

```{R,message=FALSE, warnings=FALSE, echo = FALSE}

# cut off variables at elbow seen in above bar plot
vi.df.red2 = vi.df2 %>% filter(imp>=0.8) 

# save objects
last = nvars
nvars = length(vi.df.red2$par)

# plot each variable found to be important
for (i in 1:nvars){
  
  # get interaction info
  info = unlist(strsplit(track[i],' - '))
  sp1 = info[1]
  p1 = as.numeric(info[2])
  sp2 = info[3]
  p2 = as.numeric(info[4])
    
  # get sites shared between species if there are any
  shared.sites = sapply(spp.list, function(site){(sp1 %in% site) & (sp2 %in% site)})
  sites.needed = sites[shared.sites]
  if (!any(shared.sites)) next
    
  # get parameter values
  dat1 = as.matrix(data2 %>% filter(species == sp1, p.name == p1, site %in% sites.needed) %>%
    dplyr::select(p.value))
  dat2 = as.matrix(data2 %>% filter(species == sp2, p.name == p2, site %in% sites.needed) %>%
    dplyr::select(p.value))
  dat3 = as.matrix(data2 %>% filter(species==sp1, p.name == p1, site %in% sites.needed) %>%
    mutate(class = ensemble %in% good.ensembles$ensemble) %>% dplyr::select(class))
  vals = data.frame(dat1=dat1, dat2=dat2, dat3=dat3)
  
  # save in list
  obj1[[i+last]] = paste(sp1, p1, '-', sp2, p2)
  
  # plot
  plt = ggplot(vals) + 
    geom_point(aes(x=dat1, y = dat2, col = as.factor(dat3))) +
    labs(x = paste(sp1, param.names[p1]), y = paste(sp2, param.names[p2]), 
         col = 'class')
  print(plt)
}

```


# Step 3: Determine significant parameters to total stand productivity for each site 

This step only includes ensembles with average relative bias less than 25%. 
Right now, there are two different ways that you can use to consider "variable importance." You can look at the significance of the variable in linear regression or you can look at the correlation between the variables. Multicollinearity could have an effect on the significance of variables, so I like to look at both. 

```{R, echo = FALSE, output}
obj2 = list()
plot.list = list()
i = 1
j = 1

cor.req = 0.6

# loop through the sites
for (loc in 1:length(sites)){
  
  # organize data for site
  life.melt = data[[loc]]$life.melt
  param.melt = data[[loc]]$param.melt
  bias.melt = data[[loc]]$bias.melt
  
  data3 = left_join(life.melt, param.melt, id = c('ensemble','year','species')) %>% 
    left_join(bias.melt, id = c('ensemble','year')) %>%
    filter(ensemble %in% good.ensembles$ensemble, site == sites[loc]) %>%
    group_by(ensemble,p.name,species) %>% summarize(grow = mean(growth), p.value = mean(p.value), die = mean(death), born = mean(birth)) %>% ungroup()

  # loop through species parameters
  for (s in 1:length(spp.list[[loc]])){
    for (p in 1:length(param.names)){
    
      # compile data
      sp = spp.list[[loc]][s]
      par = param.names[p]
      dat1 = as.matrix(data3 %>% filter(species == sp, p.name == p) %>% dplyr::select(grow))
      dat2 = as.matrix(data3 %>% filter(species == sp, p.name == p) %>% dplyr::select(p.value))
      plot = data.frame(dat1=dat1,dat2=dat2)
    
      if (sd(dat2) != 0 & sd(dat1) != 0){
        
        # use linear regression to determine significant predictors of growth
        mod = lm(dat1~dat2, data = plot)
        pval = coef(summary(mod))[dim(coef(summary(mod)))[1],4]
        cor = cor(dat2,dat1)
    
        # if predictor is significant
        #if (pval < 0.01){
        if (abs(cor) > cor.req){
          
          # add plot to plot list 
          pl = ggplot(plot) + 
            geom_smooth(aes(x=dat2, y =dat1),method = 'lm', show.legend = FALSE) + 
            geom_point(aes(x=dat2,y=dat1)) + 
            labs(x=paste(sp,par),y='average annual growth', title = sites[loc])
          plot.list[[j]] = ggplotGrob(pl)
          j = j + 1
          
          # check significance against life processes of species 
          for (slp in 1:length(spp.list[[loc]])){
            
            # collect life process data
            spplp = spp.list[[loc]][slp]
            birth.dat = as.matrix(data3 %>% filter(species == spplp, p.name == p) %>%
                                    dplyr::select(born))
            growth.dat = as.matrix(data3 %>% filter(species == spplp, p.name == p) %>%
                                     dplyr::select(grow))
            death.dat = as.matrix(data3 %>% filter(species == spplp, p.name == p) %>%
                                     dplyr::select(die))
            
            # check correlations
            if (sd(birth.dat) != 0 & abs(cor(dat2, birth.dat)) > cor.req){
              obj2[[i]] = c(loc, sp, par, spplp, 'birth', cor(dat2, birth.dat))
              i = i + 1
            }
            if (sd(growth.dat) != 0 & abs(cor(dat2, growth.dat)) > cor.req){
              obj2[[i]] = c(loc, sp, par, spplp, 'growth', cor(dat2, growth.dat))
              i = i + 1
            }
            if (sd(death.dat) != 0 & abs(cor(dat2, death.dat)) > cor.req){
              obj2[[i]] = c(loc, sp, par, spplp, 'death', cor(dat2, death.dat))
              i = i + 1
            }
          }
        }
      }
    }
  }
}

# plotting in grid 
splits = rep(2, floor(length(plot.list)/2))
if(length(plot.list)%%2 != 0) inds = c(splits, length(plot.list)%%2)
inds = cumsum(splits)

start = 1
for (ind in inds){
  subset = plot.list[start:ind]
  grid.arrange(grobs = subset, ncol = 2)
  start = ind + 1
}

```

# Step 4: Plot model error over time for each site 

## A. Total modiel bias over time
Right now, only good ensembles are included in this part of the analysis. Bias is relative error of forecast [(forecast - observed)/observed]. 

```{R, echo = FALSE}
# loop through sites
for (loc in 1:length(sites)){
  
  # get data 
  bias.melt = data[[loc]]$bias.melt
  
  # print plot
  print(bias.melt %>% filter(site == sites[loc], ensemble %in% good.ensembles$ensemble) %>%
    ggplot(aes(x = year + 1960, y = bias, col = ensemble)) +
      ylim(-1,1) +
      geom_point(show.legend = FALSE) +
      labs(title = paste(sites[loc],'- model error over time'), x = 'year', y = 'relative model bias'))
}
```

## B. Species-level bias over time

```{R}
# loop through sites
for (loc in 1:length(sites)){
  
  plot.list = list()
  
  # loop through all species at site
  for (s in 1:length(spp.list[[loc]])){
    
    sp = spp.list[[loc]][s]
  
    # gather and organize data 
    data4 = data[[loc]]$run.list[[s]] %>% 
      dplyr::select(ens,bias,year) %>% 
      filter(ens %in% good.ensembles$ensemble)
    
    # add plot to list for site
    pl = ggplot(data4) + 
      geom_point(aes(x = year, y = bias, col = ens), show.legend = FALSE) + 
      ylim(-0.5,0.5) + 
      labs(title = sp)
    plot.list[[s]] = ggplotGrob(pl)
  }
  
  # graph each site as a grid 
  grid.arrange(grobs = plot.list, ncol = 2)
}

```

# Step 5: Investigate significant environmental conditions for the productivity of each species

We only consider good ensembles in this section. 
Variables are considered significant subject to a significance level of 1%.

## A. Consider relationship between each variable and species growth. Look at each species individually. If a non-linear relationship seems appropriate, transform the specified variable for the species in the next step.

```{R, echo = FALSE, messages = FALSE, warnings = FALSE}
## ADJUST SPECIES HERE
sp = 1
spec = all.spp[sp]

# gather data
data.viz = run.list[[sp]] %>% filter(ens %in% good.ensembles$ensemble)
data.viz$dominant = as.factor(data.viz$dominant)
vars = names(data.viz)[-c(1,2,5,6,7)]
dat2 = as.matrix(data.viz %>% dplyr::select(pred))

for (v in 1:length(vars)){
  var = vars[v]
  dat1 = as.matrix(data.viz %>% dplyr::select(var))
  
  # check to make sure it will be considered
  if (var == 'dominant' & length(unique(dat1)) < 2) next
  if (var != 'dominant'){
    if (sd(dat1) == 0) next
    if (length(unique(dat1)) < 2) next
  } 
  
  df = data.frame(dat2 = dat2, dat1 = dat1)
  pl = ggplot(df) + 
    geom_point(aes(x = dat1, y = dat2)) +
    labs(title = var, x = var, y = 'predicted relative annual growth')
  print(pl)
}

```

### B. Perform multiple linear regression analysis to identify significant predictors and interaction terms for species growth

```{R, echo = FALSE}
# save objects
obj4 = list()

# loop through all species across sites
for (sp in 1:length(all.spp)){
  
  # gather data
  data5 = run.list[[sp]] %>% filter(ens %in% good.ensembles$ensemble)
  
  # if there is only value for dominant, can't use in regression 
  data5$dominant = as.factor(data5$dominant)
  vars = names(data5)[-c(1,2,3,5,6,7)]
  if (length(unique(data5$dominant))<2){
    vars = names(data5)[-c(1,2,3,5,6,7,19)]
  }
  data5.red = data5 %>% select(vars,pred)
  
  # use multiple linear regression to identify single significant predictors
  mod.spp = lm(pred~., data = data5.red)
  
  # determine predictors that are found to be significant 
  sig.params = as.vector(which(coef(summary(mod.spp))[-1,4] < 0.01))
  sig.vars = names(which(coef(summary(mod.spp))[-1,4] < 0.01))
  if (length(which(sig.params %in% c(13,14,15))) > 0){
    sig.vars = sig.vars[-c(which(sig.params %in% c(13,14,15)))]
    sig.vars = c(sig.vars, 'dominant')
  }
  
  # identify important interactions between variables
  inter.list = list()
  int = 1
  
  for (v1 in 1:(length(vars)-1)){
    var1 = vars[v1]
    for (v2 in (v1+1):length(vars)){
      
      # fit full interaction model
      var2 = vars[v2]
      eq = paste0("pred~",var1,"*",var2)
      mod.inter = lm(as.formula(eq), data =  data5.red)
      
      # get interaction term values
      term = grep(':',names(coef(summary(mod.inter))[,1]))
      if (length(term)==0) next
      
      # adjust for factor variable (dominants)
      if (var2 == 'dominant' | var1 == 'dominant'){
        if (any(coef(summary(mod.inter))[term,4] < 0.01)){
          inter.list[[int]] = c(var1,var2)
          int = int +1 
        }
      }else{
        if (coef(summary(mod.inter))[term,4] < 0.01){
          inter.list[[int]] = c(var1,var2)
          int = int + 1
        }
      }
    }
  }
  
  # refit the model and only take ones that are actually helpful 
  sing.part = paste(sig.vars, collapse='+')
  inter.part = paste(sapply(inter.list, function(x){paste(x,collapse='*')}), collapse = '+')
  
  if (sing.part == '' & inter.part == ''){
    obj4[[sp]] = NA
    next
  }
  if (sing.part != '' & inter.part == '') eq = paste0('pred~',sing.part)
  if (sing.part == '' & inter.part != '') eq = paste0('pred~',inter.part)
  if (sing.part != '' & inter.part != '') eq = paste0('pred~',sing.part,'+',inter.part)

  mod.full = lm(as.formula(eq), data5.red)
  
  # save significant info for species 
  to_save = names(which(coef(summary(mod.full))[-1,4] < 0.01))
  
  # adjust for dominant 
  to_change = grep('dominant',to_save)[which(!(grep('dominant', to_save) %in% grep(':', to_save)))]
  to_save[to_change] = 'dominant'
  
  if (length(to_save)==0){ to_save = NA }
  
  obj4[[sp]] = unique(to_save)
}
```

## C. Generate plots for each species and its significant predictors

```{R, echo = FALSE, warnings = FALSE}
# loop through species 
for (sp in 1:length(all.spp)){
  
  # check to make sure there are predictors
  if (is.na(obj4[[sp]])) next
  
  # get predictors needed
  preds = obj4[[sp]]
  inter.terms = grep(':', preds)
  sig.terms = ifelse(length(inter.terms) > 0, preds[-c(inter.terms)], preds)
  inter.terms = preds[inter.terms]
  
  # separate interaction terms 
  inter.pairs = lapply(inter.terms,function(term){
    terms = strsplit(term,':')
    terms[grep('dominant',terms)] = 'dominant'
    return(terms)}
    )

  # concatenate 
  all.terms = unique(c(sig.terms, unlist(inter.pairs)))
  
  # get data 
  data5.plot = run.list[[sp]] %>%
    filter(ens %in% good.ensembles$ensemble) %>% 
    mutate(dominant = as.factor(dominant)) %>%
    select(pred, all.terms)
  
  min = min(data5.plot$pred) 
  max = max(data5.plot$pred)
  breaks = c(min-0.1, min/2, 0, max/2, max+0.1)
  data5.plot$breaks = as.factor(.bincode(data5.plot$pred,breaks, TRUE))
  
  plot.list = list()
  i = 1 
  
  # plot individual sig predictors vs. growth 
  if (length(sig.terms) > 0){
    for (p in 1:length(sig.terms)){
      var.plot = sig.terms[p]
      pl = ggplot(data5.plot, aes_string(x=var.plot,y='pred'), col = 'darkgreen') + 
        geom_point() + 
        geom_smooth(method='lm') + 
        labs(x = var.plot, y = 'predicted growth', title = all.spp[sp])
      plot.list[[i]] = ggplotGrob(pl)
      i = i + 1
    }
  }
  
  # plot interaction terms 
  if (length(inter.pairs) > 0){
    for (p in 1:length(inter.pairs)){
      var1.plot = inter.pairs[[p]][[1]][1]
      var2.plot = inter.pairs[[p]][[1]][2]
      pl = ggplot(data5.plot, aes_string(x=var1.plot,y=var2.plot)) +
        geom_point(aes(col=breaks)) +
        labs(x=var1.plot, y=var2.plot, title = all.spp[sp]) + 
        scale_color_manual(values = c('1'='yellow','2'='orange','3'='red','4'='purple'))
      plot.list[[i]] = ggplotGrob(pl)
      i = i + 1
    }
  }
  
  # plot all 
  if (length(plot.list)>0){
    grid.arrange(grobs = plot.list, ncol = 2)
  }
  
  # plot parallel coordinates
  if (length(all.terms) > 2){
      print(ggparcoord(data = data5.plot, columns = 2:(ncol(data5.plot)-1), groupColumn = ncol(data5.plot), title = all.spp[sp]))
  }
}

```
 
# Step 6: Identify environmental conditions under which LINKAGES performs poorly for each species. 

## A. Consider importance ranking of all environmental variables for predicting accuracy of model forecasts for each species biomass.  

We consider all ensembles in this section.

```{R,message=FALSE, warnings=FALSE, echo = FALSE}

# determine how many variables to consider for each species
# if there is no plot for a species, it signifies that the ensembles that included the species were all considered "accurate" or "inaccurate"
var_nums = c(1,1,1,1,0,0)

# save objects 
obj5 = list()

# loop through all species across sites
for (sp in 1:length(all.spp)){
  
  # gather data of variables for species
  data6 = run.list[[sp]]
  data6$class = ifelse(data6$bias<=0.25, 1, 0)
  if (length(unique(data6$dominant)) < 2){
    data6$dominant = as.factor(data6$dominant)
    data6 = data6 %>% dplyr::select(-ens, -year, -lat, -lon, -pred, -bias, -weight)
  }else{
    data6 = data6 %>% dplyr::select(-ens, -year, -lat, -lon, -pred, -bias, -weight, -dominant)
  }
  
  # are there inaccurate ensembles?
  if (length(unique(data6$class))<2) next
  
  # barplot of importance rankings
  forest3=randomForest(as.factor(class)~., data=data6, na.action = na.omit)
  vi_imp3 = importance(forest3)
  vi_sort3 = sort(vi_imp3, decreasing = TRUE, index.return=TRUE)
  vi.df3 = data.frame(par = rownames(vi_imp3)[vi_sort3$ix], imp = vi_sort3$x)
  plot = barplot(vi.df3$imp, main = sp)
}
```
Consider barplot to determine how many variables we want to consider further. 

## B. Plot those variables that have been deemed to be "important."

```{R, message=FALSE, warnings=FALSE, echo = FALSE}

# from the barplots above, determine how many variables we want to keep for each species
cuts = c(1,1,1,NA,3,1)

# plot variables found to be important
for (sp in 1:length(all.spp)){
  
  # cutoff for this species data
  if (is.na(cuts[sp])) next
  cut = cuts[sp]
  
  spp = all.spp[sp]
  
  # gather data again
  data6 = run.list[[sp]]
  data6$class = ifelse(data6$bias<=0.25, 1, 0)
  if (length(unique(data6$dominant)) < 2){
    data6$dominant = as.factor(data6$dominant)
    data6 = data6 %>% dplyr::select(-ens, -year, -lat, -lon, -pred, -bias, -weight)
  }else{
    data6 = data6 %>% dplyr::select(-ens, -year, -lat, -lon, -pred, -bias, -weight, -dominant)
  }

  # barplot of importance rankings
  forest3=randomForest(as.factor(class)~., data=data6, na.action = na.omit)
  vi_imp3 = importance(forest3)
  vi_sort3 = sort(vi_imp3, decreasing = TRUE, index.return=TRUE)
  vi.df3 = data.frame(par = rownames(vi_imp3)[vi_sort3$ix], imp = vi_sort3$x)
  
  vi.df3$par = unlist(strsplit(toString(vi.df3$par), ', '))
  
  for (j in 1:cut){
    dat1 = data6[,vi.df3$par[j]]
    dat2 = data6$class
    df = data.frame(dat1=dat1,dat2=dat2)
    plt = ggplot(df) + geom_histogram(aes(x=dat1,fill=as.factor(dat2))) +
      labs(title = paste(spp,vi.df3$par[j]), x = 'value')
    print(plt)
  }
}

```

## C. Consider pairs of environmental variables using importance ranking. 

HACK: Removing factor variable from data6 for use with importance ranking because it does not work well with multiplication step. 

```{R,message=FALSE, warnings=FALSE, echo = FALSE}

# save objects
data.save = list()

# loop through all species across sites
for (sp in 1:length(all.spp)){
  
  # gather data of variables for species
  data6 = run.list[[sp]]
  class = ifelse(data6$bias<=0.25,1,0)
  #if (length(unique(data6$dominant)) < 2){
  #  data6$dominant = as.factor(data6$dominant)
  #  data6 = data6 %>% dplyr::select(-ens, -year, -lat, -lon, -pred, -bias, -weight)
  #}else{
    data6 = data6 %>% dplyr::select(-ens, -year, -lat, -lon, -pred, -bias, -weight, -dominant)
  #}
  
  if (length(unique(class))<2) next
  
  nvars = length(names(data6))
  vnames = names(data6)
  df4 = matrix(NA,length(class),(1+nvars^2))
  names = c('class')
  df4[,1] = class
  
  # calculate interaction terms
  ind = 2
  for (i in 1:(nvars-1)){
    for (j in (i+1):nvars){
      df4[,ind] = data6[,i] * data6[,j]
      ind = ind + 1
      names = c(names, paste0(vnames[i],'_',vnames[j]))
    }
  }
  
  df4 = df4[,1:(ind-1)]
  colnames(df4) = names
  df4 = as.data.frame(df4)
  data.save[[sp]] = df4

  # find importance rankings for each parameter
  forest4=randomForest(factor(class)~., data=df4, na.action=na.omit)
  vi_imp4 = importance(forest4)
  vi_sort4 = sort(vi_imp4, decreasing = TRUE, index.return=TRUE)
  vi.df4 = data.frame(par = rownames(vi_imp4)[vi_sort4$ix], imp = vi_sort4$x)
  print(barplot(vi.df4$imp, main = sp))
}


```
Consider barplot to determine how many pairs we want to consider further. 

## D. Plot those pairs of variables that have been deemed to be "important."

```{r,message=FALSE, warnings=FALSE, echo = FALSE}

# define cutoffs for each species
cuts = c(2,1,1,NA,1,1)

for (sp in 1:length(all.spp)){
  
  data7 = data.save[[sp]]
  if (is.na(cuts[sp])) next
  
  data.plot = run.list[[sp]]
  data.plot$class = ifelse(data.plot$bias<=0.25,1,0)
  
  # find importance rankings for each parameter
  forest4 = randomForest(factor(class)~., data=data7, na.action=na.omit)
  vi_imp4 = importance(forest4)
  vi_sort4 = sort(vi_imp4, decreasing = TRUE, index.return=TRUE)
  vi.df4 = data.frame(par = rownames(vi_imp4)[vi_sort4$ix], imp = vi_sort4$x)
  
  for (i in 1:cuts[sp]){
    
    # extract the required variables 
    vars = strsplit(toString(vi.df4$par[i]), split = '_')
    var1 = vars[[1]][1]
    var2 = vars[[1]][2]
    
    # create plot
    pl = ggplot(data = data.plot, aes(col=as.factor(class))) +
      geom_point(aes_string(x=var1, y=var2)) + 
      labs(col = 'Class', title = all.spp[sp])
    print(pl)
  }
}

```


